version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
      - ./otel-collector-config.yaml:/collector-config.yaml
    command: ["--config=/collector-config.yaml"]
    expose:
      - "4318"
    ports:
      - "4318:4318"
