# Use an OpenJDK image
FROM openjdk:17-jdk

# Set working directory inside the container
WORKDIR /app

# Copy the jar file into the container
COPY target/otel-spring-boot-demo-0.0.1-SNAPSHOT.jar app.jar

# Expose default Spring Boot port
EXPOSE 8080

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]
