spring:
  application:
    name: otel-spring-boot-demo

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      otlp:
        enabled: true
        url: http://localhost:4318/v1/metrics
        step: 30s

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
  resource:
    attributes:
      service.name: otel-spring-boot-demo
